# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HostManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cmdline', models.CharField(max_length=256)),
                ('start', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(default='', max_length=4096)),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=8, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('finishAt', models.DateTimeField(default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManage.CommandTask')),
                ('taskhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.CharField(max_length=256)),
                ('remote_file', models.CharField(max_length=256)),
                ('on_exists', models.CharField(choices=[('ov', '覆盖'), ('ba', '备份'), ('sk', '跳过')], max_length=4)),
                ('start', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=8, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('finishAt', models.DateTimeField(default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManage.FileTask')),
                ('taskhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
    ]
