# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HostManage', '0003_auto_20170115_1732'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cmdline', models.CharField(max_length=256)),
                ('start', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('finishAt', models.DateTimeField(auto_now=True)),
                ('commandtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManage.CommandTask')),
                ('taskhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.CharField(max_length=256)),
                ('start', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('finishAt', models.DateTimeField(auto_now=True)),
                ('commandtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManage.CommandTask')),
                ('taskhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
    ]
