# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtask',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filetask',
            name='on_exists',
            field=models.CharField(choices=[('ov', '覆盖'), ('ba', '备份')], default='ov', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetask',
            name='remote_file',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetask',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filetaskprogress',
            name='finishAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
