# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SystemManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=32)),
                ('cmdline', models.CharField(max_length=32)),
                ('cmdArgs', models.CharField(blank=True, max_length=128, null=True)),
                ('startCommand', models.CharField(max_length=256)),
                ('stopCommand', models.CharField(max_length=256)),
                ('restartCommand', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=128)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('remark', models.TextField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField(default=False)),
                ('isDel', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('hostgroup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SystemManage.HostGroup')),
                ('onTopof', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostAppliction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OF', '未启动'), ('ON', '运行中'), ('NI', '未安装')], default='OF', max_length=2)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Application')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS', models.CharField(max_length=64)),
                ('cpu_version', models.CharField(max_length=128)),
                ('cpu_thd_cnt', models.CharField(max_length=4)),
                ('MAC', models.CharField(max_length=32)),
                ('mem_total', models.CharField(max_length=16)),
                ('kernal_version', models.CharField(max_length=128)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
        migrations.CreateModel(
            name='HostStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_sys', models.FloatField()),
                ('cpu_usr', models.FloatField()),
                ('cpu_idle', models.FloatField()),
                ('mem_total', models.IntegerField()),
                ('mem_used', models.IntegerField()),
                ('mem_free', models.IntegerField()),
                ('mem_avai', models.IntegerField()),
                ('net_sent', models.IntegerField()),
                ('net_recv', models.IntegerField()),
                ('disk_write', models.IntegerField()),
                ('disk_read', models.IntegerField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManage.Host')),
            ],
        ),
        migrations.CreateModel(
            name='LogCleanConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configName', models.CharField(max_length=32, verbose_name='配置名称')),
                ('host_id', models.IntegerField(default=-1)),
                ('LogPath', models.CharField(help_text='单个目录一行', max_length=256, verbose_name='清理日志路径')),
                ('compress', models.BooleanField(default=False, verbose_name='Gzip压缩')),
                ('copytruncate', models.BooleanField(default=True, verbose_name='截断打开的日志')),
                ('create', models.BooleanField(default=True, verbose_name='完成后创建日志文件')),
                ('mode_owner_group', models.CharField(blank=True, default='', help_text='留空保持原来的模式，属组', max_length=64, null=True, verbose_name='创建文件的模式，属组')),
                ('delaycompress', models.BooleanField(default=False, verbose_name='是否延时压缩')),
                ('ifempty', models.BooleanField(default=True, verbose_name='转储空日志')),
                ('olddir', models.BooleanField(default=False, verbose_name='指定转储日志目录')),
                ('directory', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='转储日志目录')),
                ('missingok', models.BooleanField(default=True, verbose_name='日志不存在时不报错')),
                ('prerotate', models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='转储前执行脚本')),
                ('postrotate', models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='转储后执行脚本')),
                ('cycle', models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='weekly', max_length=8, verbose_name='转储周期')),
                ('rotate', models.IntegerField(default=4, null=True, verbose_name='保留转储次数')),
                ('size', models.CharField(default='20MB', help_text='可以指定 bytes (缺省)以及KB (sizek)或者MB (sizem)', max_length=16, verbose_name='转储大小阈值')),
                ('sync', models.BooleanField(default=False)),
                ('isDel', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='logcleanconfig',
            unique_together=set([('host_id', 'configName')]),
        ),
    ]
