# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.CharField(default='root', max_length=32),
            preserve_default=False,
        ),
    ]
