# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManage', '0002_host_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='MAC',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SystemManage.HostGroup'),
        ),
    ]
