#!/bin/bash
# chkconfig: 2345 66 36
# /etc/rc.d/init.d/opt/python
# description: FreeEye Agent
#
case "$1" in
  start)
        echo -n "FreeEye Agent "
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Starting python ." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        cd  /usr/local/FreeEye
        python FreeEye_Agent_py2.py &
        echo "Done."
        echo ""
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Finished." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        touch /var/lock/FreeEye_Agent.lock
        ;;
  stop)
        echo -n "Shutting Down python Listeners: "
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Shutting Down python." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        killall -9 FreeEye_Agent_py2.py
        echo "Done."
        rm -f /var/lock/FreeEye_Agent.lock
        echo "Done."
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Finished." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        ;;
    restart)
        echo -n "Shutting Down python Listeners: "
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Shutting Down python." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
    echo "python"
        killall -9 FreeEye_Agent_py2.py
        echo "Done."
        rm -f /var/lock/FreeEye_Agent.lock
        echo "Done."
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Finished." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        echo -n "FreeEye Agent "
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Starting python ." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        cd  /usr/local/FreeEye
        python FreeEye_Agent_py2.py &
        echo "Done."
        echo ""
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        date +"! %T %a %D : Finished." >>/var/log/FreeEye_Agent.log
        echo "---------------------------------------------------------------------------------" >>/var/log/FreeEye_Agent.log
        touch /var/lock/FreeEye_Agent.lock
        ;;
  *)
  echo "Usage: python { start | stop | restart }"
  exit 1
esac
exit 0
