# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='isDel',
            field=models.BooleanField(default=False),
        ),
    ]
