# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0003_auto_20170112_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
