# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainFrame', '0005_auto_20170112_1859'),
        ('MainFrame', '0005_auto_20170112_1857'),
    ]

    operations = [
    ]
